#!/usr/bin/env python
import datetime
import holidays
import ephem
from dateutil import tz

## Adjustable Params
my_holidays = holidays.UnitedStates()
my_timezone = 'America/Anchorage'
my_latitude = '61.217'
my_longitude = '-149.9'

## Program begins here
from_zone = tz.tzutc()
to_zone = tz.tzlocal()
#to_zone = tz.gettz(my_timezone)	# if tzlocal doesn't work

o = ephem.Observer()
o.lat, o.long, o.date = my_latitude, my_longitude, datetime.datetime.utcnow()
sun = ephem.Sun(o)

print "Sunrise/Sunset for " + my_timezone

utc = o.next_rising(sun)
utc = utc.datetime()
utc = utc.replace(tzinfo=from_zone)
local = utc.astimezone(to_zone)

weekno = datetime.datetime.weekday(local)
if weekno < 5:
  if local in my_holidays:
    print "Holiday"
  else:
    print "Workday Sunrise:", local

else:
  print "Weekend"

utc = o.next_setting(sun)
utc = utc.datetime()
utc = utc.replace(tzinfo=from_zone)
local = utc.astimezone(to_zone)
print "sunset:", local

